### ISSUE TITLE
Tree structure not shown

### ISSUE THREAD

**Issue by evgenyfadeev** [McSodbrenner/vscode-better-open-editors#16]
For my Python project the better open files shows just a list of files, there isn't a tree, however the items are ordered correctly. 

The JS projects are displayed as expected.

Maybe the feature depends on the presence of certain file? Why not just use the directory structure to produce the corresponding tree output?

[edit]

I found a solution to edit the glob parameter in the settings, however still IMO a better experience would be to just read the directory tree and draw a subset containing the open editors.

**Comment by McSodbrenner** [comment]
@evgenyfadeev In fact, Better Open Editors was created to improve the handling of many tabs in mono repos with very small individual projects. I suspect that especially with a lot of open tabs in a tree structure, the clarity quickly goes out the window. But I'll think about it again.
In fact the plugin listens to package files (at the moment composer.json and package.json) and just to the glob to create the structure.

@brainexcerpts
> As a side note, I would really love to have the option to display files in a flat structure, just like the built in "open editors", but hide the file paths. Currently you can put an empty string in "Package patterns" as a glob (this produce a flat structure), but file paths are still displayed. There is the "Insert Space For Last Slug" (would be nice to be able to specify how many spaces) but not a "hide file paths" options.
Interesting. At the moment I can't even imagine when that might be useful. :D Otherwise, I like to look at it.

(another completely unrelated note, the extension does not load automatically you have to go to the command palette, as a beginner I almost gave up on the extension thinking it was not working, I'm glad I found out since I really love it!)
The problem was that after installation it does not directly replace the normal "Open Editors"?

**Comment by brainexcerpts** [comment]
> The problem was that after installation it does not directly replace the normal "Open Editors"?
The "Better Open Editors" was not showing up until I did "CTRL+SHITP+P" and searched for "Better Open Editor". But maybe I was simply not noticing where it was and expecting it to replace "Open Editors" (in the doc there is a side by side view that make it look like it's the expected behavior) I guess it's more like a me issue than anything else...

> Interesting. At the moment I can't even imagine when that might be useful. :D Otherwise, I like to look at it.
Yea you wrote this extension to get a tree view in the first place so that makes sens aha, but personally I like to have uncluttered file names to simulate vertical tabs ^^ (even the standard "Open Editors" displays file paths [although there is a tedious workaround](https://github.com/microsoft/vscode/issues/81899))

**Comment by McSodbrenner** [comment]
> @McSodbrenner, thanks! It's useful extension, I'm glad I found it. I guess the issue is that the extension appears to not work out of the box for projects without composer.json and package.json files. It just seems to be broken. imho it would be best to avoid making assumptions about other people's code;).

This is from README.md: "The main purpose of the extension is to group files automatically that belong to packages." So I think I'm not making assumptions about code from others, but you about what you think this extension should be for. :) The README also describes which package files are considered. If more are desired, I can of course include them.

**Comment by brainexcerpts** [comment]
Yes! Thank you for making my dream come true!

2023年4月16日(日) 22:13 Christoph Erdmann ***@***.***>:
